Milestone 3/ThrowawayProject/ThrowawayProject/Models/Athlete.cs
namespace ThrowawayProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Athlete
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Athlete()
        {
            RaceResults = new HashSet<RaceResult>();
        }

        public int ID { get; set; }

        [Required]
        [StringLength(50)]
        public string NAME { get; set; }

        [Required]
        [StringLength(20)]
        public string GENDER { get; set; }

        public int? TeamID { get; set; }

        public virtual Team Team { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RaceResult> RaceResults { get; set; }
    }
}

Milestone 3/ThrowawayProject/ThrowawayProject/Controllers/AthletesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThrowawayProject.DAL;
using ThrowawayProject.Models;

namespace ThrowawayProject.Controllers
{
    public class AthletesController : Controller
    {
        private AthleteContext db = new AthleteContext();

        // GET: Athletes
        public ActionResult Index()
        {
                 return View();
        }

        [HttpPost]
        public ActionResult Index(string searchString)
        {
            {
                IQueryable<Athlete> players = db.Athletes;
                ViewBag.Message = "Sorry no matching athlete has been found";

                if (!String.IsNullOrEmpty(searchString))
                {
                   players = players.Where(s => s.NAME.Contains(searchString));
                }

                return View(players.ToList());
            }
        }


        // GET: Detail results (uses a ViewModel in Model folder)
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Athlete player = db.Athletes.Find(id);
            if ( player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        public ActionResult List()
        {
            var athletes = db.Athletes;
            return View(athletes.ToList());
        }
    }
}

Milestone 3/ThrowawayProject/ThrowawayProject/Views/Athletes/Details.cshtml
@model ThrowawayProject.Models.Athlete

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @{<text>Team Name</text>}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team.NAME)
        </dd>

        <dt>
            @{<text>Athlete Name</text>}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NAME)
        </dd>

        <dt>
            @{<text>Gender</text>}
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GENDER)
        </dd>

    </dl>
</div>

<div class="row">

    <div class="col-md-7 tableStyle">
        <h4 class="StockInfo"> Athlete Results </h4>
        <div class="row">
            <div class="col-md-10">
                <table class="table">
                    <tr>
                        <th>
                            @{<text>Race Type</text>}
                        </th>
                        <th>
                            @{<text>Time Completed</text>}
                        </th>
                    </tr>

                    @foreach (var item in Model.RaceResults)
                    {
                        <tr>
                            <td>
                                @item.NAME
                            </td>
                            <td>
                                @item.TIME
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>

<p>
    |
    @Html.ActionLink("Back to List", "Index")
</p>

Milestone 3/ThrowawayProject/ThrowawayProject/Views/Athletes/Index.cshtml
@model IEnumerable<ThrowawayProject.Models.Athlete>

@{
    ViewBag.Title = "Search for Athletes";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search for your favorite Athlete below</h2>


<br />
@using (Html.BeginForm("Index", "Athletes", FormMethod.Post))
{
    <div class="container-fluid" style="font-size:large;" id="searchBox">
        Enter your search here:
        @Html.TextBox("searchString", null, new { style = "width: 4000px; height: 30px;", placeholder = "   partial matches will be found" })
        <input type="submit" id="searchBoxID" value="Search Now" />
    </div>
    <br />

    if (Model != null)
    {
        if (Model.Count() != 0) // checking to make sure that there are items in the model.
        {

            <table class="table table-striped table-dark" id="resultsTable">
                <tr>
                    <th>@Html.Label("Name of the Item")</th>
                    <th>@Html.Label("League")</th>
                    <th> </th>
                    <th>@Html.Label(" Details Below")</th>
                </tr>

                @foreach (var item in Model) // Iterate through all items in the model to produce search results.
                {
                    <tr>

                        <td>

                            @Html.DisplayFor(modelItem => item.NAME)
                        </td>
                        <td>@Html.DisplayFor(modelItem => item.GENDER)</td>
                        <td>
                        <td>
                            @Html.ActionLink("Details", "Details", new { id = item.ID })
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <div id="searchAgain">
                @Html.ActionLink("Start a new search", "Index")
            </div>
            <div class="container">
                <img src="~/Images/notFound.png" id="notFoundPhoto" />
            </div>

        }

    }

}

Milestone 3/ThrowawayProject/ThrowawayProject/Views/Athletes/List.cshtml
@model IEnumerable<ThrowawayProject.Models.Athlete>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NAME)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NAME)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID })
        </td>
    </tr>
}

</table>